#include "CondFormats/DataRecord/interface/HeterogeneousHGCalPositionsConditionsRecord.h"
#include "FWCore/Framework/interface/eventsetuprecord_registration_macro.h"

EVENTSETUP_RECORD_REG(HeterogeneousHGCalPositionsConditionsRecord);
